name: "CI"
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Cache Nix dependencies
        run: |
          nix develop -j 4 -c echo
      - name: Build 🔨
        id: build
        run: |
          nix build -j auto -L
